/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */
package acJavaCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int FLOATDCL = 7;
  /** RegularExpression Id. */
  int INTDCL = 8;
  /** RegularExpression Id. */
  int PRINT = 9;
  /** RegularExpression Id. */
  int ASSIGN = 10;
  /** RegularExpression Id. */
  int INUM = 11;
  /** RegularExpression Id. */
  int FNUM = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int ID = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"f\"",
    "\"i\"",
    "\"p\"",
    "\"=\"",
    "<INUM>",
    "<FNUM>",
    "<DIGIT>",
    "<ID>",
    "\";\"",
  };

}
